version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  exclusions:
    generated: lax
formatters:
  enable:
    - gofmt
    - goimports
